#!/bin/bash
# GL Architecture Consolidation Script
# Generated by GL Consolidation Planner
# Date: 2026-01-21T04:04:43.517240

set -e  # Exit on error

# Backup current state
echo 'Creating backup...'
BACKUP_DIR=&quot;backups/gl-consolidation-$(date +%Y%m%d-%H%M%S)&quot;
mkdir -p &quot;$BACKUP_DIR&quot;

# 合併重複目錄 workspace/governance/GL-architecture 到 governance/GL-architecture
echo 'Merging workspace/governance/GL-architecture to governance/GL-architecture...'
cp -rn &quot;workspace/governance/GL-architecture/&quot;* &quot;governance/GL-architecture/&quot; 2>/dev/null || true

# 刪除已合併的重複目錄 workspace/governance/GL-architecture
echo 'Backing up and removing workspace/governance/GL-architecture...'
cp -r &quot;workspace/governance/GL-architecture&quot; &quot;$BACKUP_DIR/&quot; 2>/dev/null || true
rm -rf &quot;workspace/governance/GL-architecture&quot;

# 合併重複目錄 workspace/governance/layers 到 governance/layers
echo 'Merging workspace/governance/layers to governance/layers...'
cp -rn &quot;workspace/governance/layers/&quot;* &quot;governance/layers/&quot; 2>/dev/null || true

# 刪除已合併的重複目錄 workspace/governance/layers
echo 'Backing up and removing workspace/governance/layers...'
cp -r &quot;workspace/governance/layers&quot; &quot;$BACKUP_DIR/&quot; 2>/dev/null || true
rm -rf &quot;workspace/governance/layers&quot;

# 合併重複目錄 workspace/governance/meta-spec 到 governance/meta-spec
echo 'Merging workspace/governance/meta-spec to governance/meta-spec...'
cp -rn &quot;workspace/governance/meta-spec/&quot;* &quot;governance/meta-spec/&quot; 2>/dev/null || true

# 刪除已合併的重複目錄 workspace/governance/meta-spec
echo 'Backing up and removing workspace/governance/meta-spec...'
cp -r &quot;workspace/governance/meta-spec&quot; &quot;$BACKUP_DIR/&quot; 2>/dev/null || true
rm -rf &quot;workspace/governance/meta-spec&quot;

# 合併重複目錄 workspace/governance/sealed 到 governance/sealed
echo 'Merging workspace/governance/sealed to governance/sealed...'
cp -rn &quot;workspace/governance/sealed/&quot;* &quot;governance/sealed/&quot; 2>/dev/null || true

# 刪除已合併的重複目錄 workspace/governance/sealed
echo 'Backing up and removing workspace/governance/sealed...'
cp -r &quot;workspace/governance/sealed&quot; &quot;$BACKUP_DIR/&quot; 2>/dev/null || true
rm -rf &quot;workspace/governance/sealed&quot;

# 合併重複目錄 workspace/governance/naming-governance-v1.0.0 到 governance/naming-governance-v1.0.0
echo 'Merging workspace/governance/naming-governance-v1.0.0 to governance/naming-governance-v1.0.0...'
cp -rn &quot;workspace/governance/naming-governance-v1.0.0/&quot;* &quot;governance/naming-governance-v1.0.0/&quot; 2>/dev/null || true

# 刪除已合併的重複目錄 workspace/governance/naming-governance-v1.0.0
echo 'Backing up and removing workspace/governance/naming-governance-v1.0.0...'
cp -r &quot;workspace/governance/naming-governance-v1.0.0&quot; &quot;$BACKUP_DIR/&quot; 2>/dev/null || true
rm -rf &quot;workspace/governance/naming-governance-v1.0.0&quot;

# 合併重複目錄 workspace/governance/naming-governance-v1.0.0-extended 到 governance/naming-governance-v1.0.0-extended
echo 'Merging workspace/governance/naming-governance-v1.0.0-extended to governance/naming-governance-v1.0.0-extended...'
cp -rn &quot;workspace/governance/naming-governance-v1.0.0-extended/&quot;* &quot;governance/naming-governance-v1.0.0-extended/&quot; 2>/dev/null || true

# 刪除已合併的重複目錄 workspace/governance/naming-governance-v1.0.0-extended
echo 'Backing up and removing workspace/governance/naming-governance-v1.0.0-extended...'
cp -r &quot;workspace/governance/naming-governance-v1.0.0-extended&quot; &quot;$BACKUP_DIR/&quot; 2>/dev/null || true
rm -rf &quot;workspace/governance/naming-governance-v1.0.0-extended&quot;

# 合併重複目錄 workspace/governance/quantum-naming-v4.0.0 到 governance/quantum-naming-v4.0.0
echo 'Merging workspace/governance/quantum-naming-v4.0.0 to governance/quantum-naming-v4.0.0...'
cp -rn &quot;workspace/governance/quantum-naming-v4.0.0/&quot;* &quot;governance/quantum-naming-v4.0.0/&quot; 2>/dev/null || true

# 刪除已合併的重複目錄 workspace/governance/quantum-naming-v4.0.0
echo 'Backing up and removing workspace/governance/quantum-naming-v4.0.0...'
cp -r &quot;workspace/governance/quantum-naming-v4.0.0&quot; &quot;$BACKUP_DIR/&quot; 2>/dev/null || true
rm -rf &quot;workspace/governance/quantum-naming-v4.0.0&quot;

# 統一命名風格: GL-EXECUTION-MODE.yaml -> gl-execution-mode.yaml
echo 'Renaming GL-EXECUTION-MODE.yaml to gl-execution-mode.yaml...'
git mv &quot;GL-EXECUTION-MODE.yaml&quot; &quot;gl-execution-mode.yaml&quot; 2>/dev/null || mv &quot;GL-EXECUTION-MODE.yaml&quot; &quot;gl-execution-mode.yaml&quot;

# 統一命名風格: GL-MAINLINE-INTEGRATION.md -> gl-mainline-integration.md
echo 'Renaming GL-MAINLINE-INTEGRATION.md to gl-mainline-integration.md...'
git mv &quot;GL-MAINLINE-INTEGRATION.md&quot; &quot;gl-mainline-integration.md&quot; 2>/dev/null || mv &quot;GL-MAINLINE-INTEGRATION.md&quot; &quot;gl-mainline-integration.md&quot;

# 統一命名風格: GL_DIRECTORY_NAMING_SPEC.yaml -> gl-directory-naming-spec.yaml
echo 'Renaming governance/GL-architecture/GL_DIRECTORY_NAMING_SPEC.yaml to governance/GL-architecture/gl-directory-naming-spec.yaml...'
git mv &quot;governance/GL-architecture/GL_DIRECTORY_NAMING_SPEC.yaml&quot; &quot;governance/GL-architecture/gl-directory-naming-spec.yaml&quot; 2>/dev/null || mv &quot;governance/GL-architecture/GL_DIRECTORY_NAMING_SPEC.yaml&quot; &quot;governance/GL-architecture/gl-directory-naming-spec.yaml&quot;

# 統一命名風格: GL_LAYERS.yaml -> gl-layers.yaml
echo 'Renaming governance/GL-architecture/GL_LAYERS.yaml to governance/GL-architecture/gl-layers.yaml...'
git mv &quot;governance/GL-architecture/GL_LAYERS.yaml&quot; &quot;governance/GL-architecture/gl-layers.yaml&quot; 2>/dev/null || mv &quot;governance/GL-architecture/GL_LAYERS.yaml&quot; &quot;governance/GL-architecture/gl-layers.yaml&quot;

# 統一命名風格: GL_SEMANTIC_STABILIZATION.yaml -> gl-semantic-stabilization.yaml
echo 'Renaming governance/GL-architecture/GL_SEMANTIC_STABILIZATION.yaml to governance/GL-architecture/gl-semantic-stabilization.yaml...'
git mv &quot;governance/GL-architecture/GL_SEMANTIC_STABILIZATION.yaml&quot; &quot;governance/GL-architecture/gl-semantic-stabilization.yaml&quot; 2>/dev/null || mv &quot;governance/GL-architecture/GL_SEMANTIC_STABILIZATION.yaml&quot; &quot;governance/GL-architecture/gl-semantic-stabilization.yaml&quot;

# 統一命名風格: GL_MAPPING.csv -> gl-mapping.csv
echo 'Renaming governance/GL-architecture/GL_MAPPING.csv to governance/GL-architecture/gl-mapping.csv...'
git mv &quot;governance/GL-architecture/GL_MAPPING.csv&quot; &quot;governance/GL-architecture/gl-mapping.csv&quot; 2>/dev/null || mv &quot;governance/GL-architecture/GL_MAPPING.csv&quot; &quot;governance/GL-architecture/gl-mapping.csv&quot;

# 統一命名風格: GL_FILESYSTEM_MAPPING.yaml -> gl-filesystem-mapping.yaml
echo 'Renaming governance/GL-architecture/GL_FILESYSTEM_MAPPING.yaml to governance/GL-architecture/gl-filesystem-mapping.yaml...'
git mv &quot;governance/GL-architecture/GL_FILESYSTEM_MAPPING.yaml&quot; &quot;governance/GL-architecture/gl-filesystem-mapping.yaml&quot; 2>/dev/null || mv &quot;governance/GL-architecture/GL_FILESYSTEM_MAPPING.yaml&quot; &quot;governance/GL-architecture/gl-filesystem-mapping.yaml&quot;

# 統一命名風格: GL_REFACTORING_EXEC_PROMPTS.md -> gl-refactoring-exec-prompts.md
echo 'Renaming governance/GL-architecture/GL_REFACTORING_EXEC_PROMPTS.md to governance/GL-architecture/gl-refactoring-exec-prompts.md...'
git mv &quot;governance/GL-architecture/GL_REFACTORING_EXEC_PROMPTS.md&quot; &quot;governance/GL-architecture/gl-refactoring-exec-prompts.md&quot; 2>/dev/null || mv &quot;governance/GL-architecture/GL_REFACTORING_EXEC_PROMPTS.md&quot; &quot;governance/GL-architecture/gl-refactoring-exec-prompts.md&quot;

# 統一命名風格: GL_QUICKREF.md -> gl-quickref.md
echo 'Renaming governance/GL-architecture/GL_QUICKREF.md to governance/GL-architecture/gl-quickref.md...'
git mv &quot;governance/GL-architecture/GL_QUICKREF.md&quot; &quot;governance/GL-architecture/gl-quickref.md&quot; 2>/dev/null || mv &quot;governance/GL-architecture/GL_QUICKREF.md&quot; &quot;governance/GL-architecture/gl-quickref.md&quot;

# 統一命名風格: GL_DIRECTORY_NAMING_SPEC.yaml -> gl-directory-naming-spec.yaml
echo 'Renaming workspace/governance/GL-architecture/GL_DIRECTORY_NAMING_SPEC.yaml to workspace/governance/GL-architecture/gl-directory-naming-spec.yaml...'
git mv &quot;workspace/governance/GL-architecture/GL_DIRECTORY_NAMING_SPEC.yaml&quot; &quot;workspace/governance/GL-architecture/gl-directory-naming-spec.yaml&quot; 2>/dev/null || mv &quot;workspace/governance/GL-architecture/GL_DIRECTORY_NAMING_SPEC.yaml&quot; &quot;workspace/governance/GL-architecture/gl-directory-naming-spec.yaml&quot;

# 統一命名風格: GL_LAYERS.yaml -> gl-layers.yaml
echo 'Renaming workspace/governance/GL-architecture/GL_LAYERS.yaml to workspace/governance/GL-architecture/gl-layers.yaml...'
git mv &quot;workspace/governance/GL-architecture/GL_LAYERS.yaml&quot; &quot;workspace/governance/GL-architecture/gl-layers.yaml&quot; 2>/dev/null || mv &quot;workspace/governance/GL-architecture/GL_LAYERS.yaml&quot; &quot;workspace/governance/GL-architecture/gl-layers.yaml&quot;

# 統一命名風格: GL_SEMANTIC_STABILIZATION.yaml -> gl-semantic-stabilization.yaml
echo 'Renaming workspace/governance/GL-architecture/GL_SEMANTIC_STABILIZATION.yaml to workspace/governance/GL-architecture/gl-semantic-stabilization.yaml...'
git mv &quot;workspace/governance/GL-architecture/GL_SEMANTIC_STABILIZATION.yaml&quot; &quot;workspace/governance/GL-architecture/gl-semantic-stabilization.yaml&quot; 2>/dev/null || mv &quot;workspace/governance/GL-architecture/GL_SEMANTIC_STABILIZATION.yaml&quot; &quot;workspace/governance/GL-architecture/gl-semantic-stabilization.yaml&quot;

# 統一命名風格: GL_MAPPING.csv -> gl-mapping.csv
echo 'Renaming workspace/governance/GL-architecture/GL_MAPPING.csv to workspace/governance/GL-architecture/gl-mapping.csv...'
git mv &quot;workspace/governance/GL-architecture/GL_MAPPING.csv&quot; &quot;workspace/governance/GL-architecture/gl-mapping.csv&quot; 2>/dev/null || mv &quot;workspace/governance/GL-architecture/GL_MAPPING.csv&quot; &quot;workspace/governance/GL-architecture/gl-mapping.csv&quot;

# 統一命名風格: GL_FILESYSTEM_MAPPING.yaml -> gl-filesystem-mapping.yaml
echo 'Renaming workspace/governance/GL-architecture/GL_FILESYSTEM_MAPPING.yaml to workspace/governance/GL-architecture/gl-filesystem-mapping.yaml...'
git mv &quot;workspace/governance/GL-architecture/GL_FILESYSTEM_MAPPING.yaml&quot; &quot;workspace/governance/GL-architecture/gl-filesystem-mapping.yaml&quot; 2>/dev/null || mv &quot;workspace/governance/GL-architecture/GL_FILESYSTEM_MAPPING.yaml&quot; &quot;workspace/governance/GL-architecture/gl-filesystem-mapping.yaml&quot;

# 統一命名風格: GL_REFACTORING_EXEC_PROMPTS.md -> gl-refactoring-exec-prompts.md
echo 'Renaming workspace/governance/GL-architecture/GL_REFACTORING_EXEC_PROMPTS.md to workspace/governance/GL-architecture/gl-refactoring-exec-prompts.md...'
git mv &quot;workspace/governance/GL-architecture/GL_REFACTORING_EXEC_PROMPTS.md&quot; &quot;workspace/governance/GL-architecture/gl-refactoring-exec-prompts.md&quot; 2>/dev/null || mv &quot;workspace/governance/GL-architecture/GL_REFACTORING_EXEC_PROMPTS.md&quot; &quot;workspace/governance/GL-architecture/gl-refactoring-exec-prompts.md&quot;

# 統一命名風格: GL_QUICKREF.md -> gl-quickref.md
echo 'Renaming workspace/governance/GL-architecture/GL_QUICKREF.md to workspace/governance/GL-architecture/gl-quickref.md...'
git mv &quot;workspace/governance/GL-architecture/GL_QUICKREF.md&quot; &quot;workspace/governance/GL-architecture/gl-quickref.md&quot; 2>/dev/null || mv &quot;workspace/governance/GL-architecture/GL_QUICKREF.md&quot; &quot;workspace/governance/GL-architecture/gl-quickref.md&quot;

# 將根目錄 GL 檔案移至統一位置
echo 'Moving GL-UNIFIED-NAMING-CHARTER-ANALYSIS.md to governance/GL-architecture/GL-UNIFIED-NAMING-CHARTER-ANALYSIS.md...'
mkdir -p &quot;$(dirname &quot;governance/GL-architecture/GL-UNIFIED-NAMING-CHARTER-ANALYSIS.md&quot;)&quot;
git mv &quot;GL-UNIFIED-NAMING-CHARTER-ANALYSIS.md&quot; &quot;governance/GL-architecture/GL-UNIFIED-NAMING-CHARTER-ANALYSIS.md&quot; 2>/dev/null || mv &quot;GL-UNIFIED-NAMING-CHARTER-ANALYSIS.md&quot; &quot;governance/GL-architecture/GL-UNIFIED-NAMING-CHARTER-ANALYSIS.md&quot;

# 將根目錄 GL 檔案移至統一位置
echo 'Moving GL-EXECUTION-MODE.yaml to governance/GL-architecture/GL-EXECUTION-MODE.yaml...'
mkdir -p &quot;$(dirname &quot;governance/GL-architecture/GL-EXECUTION-MODE.yaml&quot;)&quot;
git mv &quot;GL-EXECUTION-MODE.yaml&quot; &quot;governance/GL-architecture/GL-EXECUTION-MODE.yaml&quot; 2>/dev/null || mv &quot;GL-EXECUTION-MODE.yaml&quot; &quot;governance/GL-architecture/GL-EXECUTION-MODE.yaml&quot;

# 將根目錄 GL 檔案移至統一位置
echo 'Moving GL-MAINLINE-INTEGRATION.md to governance/GL-architecture/GL-MAINLINE-INTEGRATION.md...'
mkdir -p &quot;$(dirname &quot;governance/GL-architecture/GL-MAINLINE-INTEGRATION.md&quot;)&quot;
git mv &quot;GL-MAINLINE-INTEGRATION.md&quot; &quot;governance/GL-architecture/GL-MAINLINE-INTEGRATION.md&quot; 2>/dev/null || mv &quot;GL-MAINLINE-INTEGRATION.md&quot; &quot;governance/GL-architecture/GL-MAINLINE-INTEGRATION.md&quot;

# 將根目錄 GL 檔案移至統一位置
echo 'Moving gl-analysis-scanner.py to governance/GL-architecture/gl-analysis-scanner.py...'
mkdir -p &quot;$(dirname &quot;governance/GL-architecture/gl-analysis-scanner.py&quot;)&quot;
git mv &quot;gl-analysis-scanner.py&quot; &quot;governance/GL-architecture/gl-analysis-scanner.py&quot; 2>/dev/null || mv &quot;gl-analysis-scanner.py&quot; &quot;governance/GL-architecture/gl-analysis-scanner.py&quot;

# 將根目錄 GL 檔案移至統一位置
echo 'Moving gl-analysis-report.json to governance/GL-architecture/gl-analysis-report.json...'
mkdir -p &quot;$(dirname &quot;governance/GL-architecture/gl-analysis-report.json&quot;)&quot;
git mv &quot;gl-analysis-report.json&quot; &quot;governance/GL-architecture/gl-analysis-report.json&quot; 2>/dev/null || mv &quot;gl-analysis-report.json&quot; &quot;governance/GL-architecture/gl-analysis-report.json&quot;

echo 'Consolidation complete!'
echo &quot;Backup saved to: $BACKUP_DIR&quot;